### Local

POST http://localhost:7071/api/autocommit
Content-Type: application/json

{
    "account": "lbugnion",
    "repo": "tests-auto-commit",
    "branch": "test-branch-01",
    "message": "Testing auto-commit 104",
    "files": [
        {
            "path": "test/test104.md",
            "content": "This is test104"
        },
        {
            "path": "test/test105.md",
            "content": "This is test105"
        }
    ]
}

### Remote

POST https://lbtest007.azurewebsites.net/api/autocommit
Content-Type: application/json
x-functions-key: qY/QfLXaazmDdLsOtzDoQwYr59HZxNH9rQJaAfnl1dXTQ8mjU1ruzA==

{
    "account": "lbugnion",
    "repo": "tests-auto-commit",
    "branch": "test-branch-01",
    "message": "Testing auto-commit 110",
    "files": [
        {
            "path": "test/test110.md",
            "content": "This is test110"
        },
        {
            "path": "test/test111.md",
            "content": "This is test111"
        }
    ]
}
