### Local

POST http://localhost:7071/api/autocommit
Content-Type: application/json

{
    "account": "lbugnion",
    "repo": "tests-auto-commit",
    "branch": "test-branch-01",
    "message": "Testing auto-commit 104",
    "files": [
        {
            "path": "test/test104.md",
            "content": "This is test104"
        },
        {
            "path": "test/test105.md",
            "content": "This is test105"
        }
    ]
}

### Remote

POST https://lbautocommit.azurewebsites.net/api/autocommit
Content-Type: application/json
x-functions-key: LdDaDnZ9Pc0U32hlEVCv/npB/HSsItfJE4GcHiB6krAVD/JBDarE9g==

{
    "account": "lbugnion",
    "repo": "tests-auto-commit",
    "branch": "test-branch-01",
    "message": "Testing auto-commit 108",
    "files": [
        {
            "path": "test/test108.md",
            "content": "This is test108"
        },
        {
            "path": "test/test109.md",
            "content": "This is test109"
        }
    ]
}
